server:
  port: 8080

spring:
  data-source:
    deal-management:
      type: com.zaxxer.hikari.HikariDataSource
      jdbc-url: ${POSTGRESQL_JDBC_URL}
      username: ${POSTGRESQL_USERNAME}
      password: ${POSTGRESQL_PASSWORD}
      test-on-borrow: true
      remove-abandoned: true
      validation-query: 'select 1;'
      driver-class-name: org.postgresql.Driver

jwt:
  issuer: r.m.khasanshin@gmail.com
  secret: bkkpPJYp4ZFCHxkzaEajTfU7RF5PUZNKuQNh2JQ4wbq2U6pMvYvFug6f5QjcLhKd
  ttl: 60
